version: '3'
services:
  redis:
    image: redis
  db:
    image: postgres:9.4
  user-api:
    container_name: user-api
    hostname: user_api
    image: user_api
    build:
      context: .
      dockerfile: ./apps/user-api/Dockerfile
      target: development
    ports:
      - "3333:3333"
    command: npx nx serve user-api
  # auth-api:
  #   image: monorepo/auth-api
  #   build: ./apps/auth-api/